- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
        tags:
        - node
  tasks:
    - name: Install zsh
      apt: name=zsh
      tags:
        - zsh
    - name: Change Shell
      shell: chsh -s `which zsh`
      tags:
        - zsh
    - name: Install ohmyzsh
      shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      tags:
        - zsh
    - name: Install stow
      apt: name=stow
      tags:
        - zsh 
    - name: Install the zsh plugin
      ansible.builtin.git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
        dest: '~/.oh-my-zsh/plugins/zsh-autosuggestions'
      tags:
        - zsh
    - name: Update zshrc
      shell: sed -i 's/(git/(git zsh-autosuggestions/' ~/.zshrc
      tags:
      - zsh
